name: 'Organization GitHub Projects'
description: 'Get Organization GitHub Projects'

inputs:
  org:
    description: 'Organization name'
    required: true
  repos:
    description: "Path to file containing list of repositories"
    required: true

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }}
      shell: bash
      working-directory: ./organization/projects
