name: 'Repositories by csv'
description: 'Get repositories by a comma seperated list of repository names'

inputs:
  org:
    description: 'Organization name'
    required: true
  repos:
    description: 'Comma seperated list of repository names'
    required: true

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }} ${{ inputs.repos }}
      shell: bash
      working-directory: ./repository/repository
