name: "Repository Ruleset"
description: "Get repository ruleset"

inputs:
  org:
    description: "Organization name"
    required: true
  repos:
    description: "Path to file containing list of repositories"
    required: true
runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }} ${{ inputs.repos }}
      shell: bash
      working-directory: ./repository/ruleset
