name: Migration assessment (JSON)

on:
  workflow_dispatch:
    inputs:
      org-name:
        description: "Please provide an org name"
        required: true
        default: "sparlant-demo-org"
    
env:
  PAT: ${{ secrets.PAT }}
  ORG_NAME: ${{ github.event.inputs.org-name }}

jobs:
  create-issue:
    name: Create Audit Issue
    runs-on: ubuntu-latest
    outputs:
      ISSUE_URL: ${{ steps.create-issue.outputs.ISSUE_URL }}
    steps:
      - name: Create Issue
        id: create-issue
        run: |
          ISSUE_URL=$(gh issue create --title "Assessment issue - $ORG_NAME" --body "" --repo $REPO)
          echo "ISSUE_URL=$ISSUE_URL" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
  lfs-audit:
    name: LFS Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Build & Run
        run: |
          cd LFS_Audit
          go build .
          ./LFSAudit audit --org-name="$ORG_NAME" --pat-token="$PAT"
      - name: Create JSON
        id: lfs-output
        run: |
          AUDIT=$(cat ./LFS_Audit/repos_audited.txt)
          RESULT=$(jq --raw-input --slurp 'split("\n") | map(select(. != ""))' LFS_Audit/repos_audited.txt | jq '[ .[] | {"repo":., "lfs": true} ]')

          gh issue comment $ISSUE_URL --body "$RESULT"

          echo $RESULT > lfs.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: lfs
          path: lfs.json
  secrets-audit:
    name: Secrets Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Run script
        id: secrets-output
        run: |
          ./Secrets_Audit/secrets_audit_json.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets.json
  apps-audit:
    name: GitHub Apps Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Run script
        run: |
          ./Apps_Audit/apps_audit_json.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: apps
          path: apps.json
  permissions-audit:
    name: Permissions Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Run script
        run: |
          ./Permissions_Audit/permissions_audit_json.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: permissions
          path: permissions.json
  visibility-audit:
    name: Visibility Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Run script
        run: |
          ./Visibility_Audit/visibility_audit_json.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: visibility
          path: visibility.json  
  projects-audit:
    name: Projects Audit
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Run script
        run: |
          ./Projects_Audit/projects_audit_json.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: projects
          path: projects.json  
  report:
    name: Report
    runs-on: ubuntu-latest
    needs: [create-issue, lfs-audit, visibility-audit, permissions-audit, apps-audit, secrets-audit, projects-audit]
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: lfs
      - uses: actions/download-artifact@v3
        with:
          name: visibility
      - uses: actions/download-artifact@v3
        with:
          name: permissions
      - uses: actions/download-artifact@v3
        with:
          name: apps
      - uses: actions/download-artifact@v3
        with:
          name: secrets
      - uses: actions/download-artifact@v3
        with:
          name: projects
      - name: Run script
        run: |
          ./report.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}
      - uses: actions/upload-artifact@v3
        with:
          name: org
          path: org.json
      - uses: actions/upload-artifact@v3
        with:
          name: repositories
          path: repositories.json
      - name: Run script
        run: |
          ./json-to-md.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_URL: ${{needs.create-issue.outputs.ISSUE_URL}}


          