name: Make generic API call

on:
  workflow_call:
    inputs:
      ORG_NAME:
        description: "Name of the organization"
        type: string
        required: true
      SCRIPT_PATH:
        type: string
        required: true
      JOB_NAME:
        type: string
        required: true
      ARTIFACT_TYPE:
        type: string
        required: true
      DOWNLOAD_ARTIFACT_NAME:
        type: string
        required: false

jobs:
  execute-script:
    name: ${{ inputs.JOB_NAME}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ inputs.ORG_NAME }}

      - uses: actions/download-artifact@v3
        if: ${{ inputs.DOWNLOAD_ARTIFACT_NAME != '' }}
        with:
          name: ${{ inputs.DOWNLOAD_ARTIFACT_NAME }}

      - name: Execute Script
        id: execute_script
        run: |
          bash ${{ inputs.SCRIPT_PATH }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          ORG_NAME: ${{ inputs.ORG_NAME }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.ARTIFACT_TYPE}}-${{ inputs.ORG_NAME }}
          path: ${{inputs.ARTIFACT_TYPE}}.json
          retention-days: 1
