name: MultiOrg Migration assessment

on:
  workflow_dispatch:
    inputs:
      org_names:
        description: "Please provide an org names separated by ,"
        required: true
        default: "SolidifyDemo"
    
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      orgs: ${{ steps.create-matrix.outputs.ORGS }}
    steps:
      - name: Create Matrix
        id: create-matrix
        run: |
          ORGS=$(echo -n "$org_names" | sed 's/ //g' | jq -cRs 'split(",")')
          echo "ORGS=$ORGS" >> "$GITHUB_OUTPUT"
        env:
          org_names: ${{ github.event.inputs.org_names }}
  audit:
    uses: ./.github/workflows/org_audit.yml
    needs: [create-matrix]
    strategy:
      matrix:
        ORG_NAME: ${{fromJson(needs.create-matrix.outputs.orgs)}}
    with:
      ORG_NAME: ${{ matrix.ORG_NAME }}
    secrets: inherit