name: GHEC EMU Migration Audit by Organization

on:
  workflow_dispatch:
    inputs:
      org_names:
        description: "Please provide comma separated list of organization names"
        required: true

jobs:
  get-orgs:
    runs-on: ubuntu-latest

    outputs:
      orgs: ${{ steps.create-matrix.outputs.orgs }}

    steps:
      - name: Create Matrix
        id: create-matrix
        run: |
          ORGS=$(echo -n "${org_names}" | sed 's/ //g' | jq -cRs 'split(",")')
          echo "orgs=${ORGS}" >> "$GITHUB_OUTPUT"
        env:
          org_names: ${{ github.event.inputs.org_names }}

  repository-audit:
    runs-on: ubuntu-latest

    needs:
      - get-orgs

    strategy:
      matrix:
        org: ${{ fromJson(needs.get-orgs.outputs.orgs) }}

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ matrix.org }}

      - name: Run repository-audit on ${{ matrix.org }}
        uses: ./organization/repositories
        id: repositories
        with:
          org: ${{ matrix.org }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Upload ${{ matrix.org }} results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.org }}-repositories
          path: reports/
          retention-days: 1

  audit:  
    runs-on: ubuntu-latest

    needs:
      - get-orgs
      - repository-audit

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        org: ${{ fromJson(needs.get-orgs.outputs.orgs) }}
        composite-action:
          # - action: repository/actions
          #   auth: githubapp
          - action: repository/actions-history
            auth: githubapp
          - action: repository/branch-protection-rules
            auth: githubapp
          - action: repository/discussions
            auth: githubapp
          - action: repository/environments
            auth: githubapp
          - action: repository/permissions
            auth: githubapp
          - action: repository/projects
            auth: githubapp
          - action: repository/teams
            auth: githubapp
          - action: repository/users
            auth: githubapp
          - action: repository/webhooks
            auth: githubapp
          - action: repository/ruleset
            auth: githubapp
          # organization/actions
          - action: organization/apps
            auth: githubapp
          - action: organization/packages
            auth: pat
          # organization/projects
          - action: organization/secrets
            auth: githubapp
          - action: organization/webhooks
            auth: githubapp



    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.ref_name }}

      - name: Download ${{ matrix.org }} repository-audit results
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.org }}-repositories
          path: reports

      - name: Get Token
        id: get_workflow_token
        if: ${{ matrix.composite-action.auth == 'githubapp' }}
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ matrix.org }}

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 18
        if: ${{ matrix.composite-action.action == 'organization/actions' }}

      - name: Run ${{ matrix.composite-action.action }} on ${{ matrix.org }}
        if: ${{ matrix.composite-action.auth == 'githubapp' }}
        run: ./script.sh ${{ matrix.org }} ${{ github.workspace }}/reports/repos.json
        shell: bash
        working-directory: ${{ matrix.composite-action.action }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Run ${{ matrix.composite-action.action }} on ${{ matrix.org }}
        if: ${{ matrix.composite-action.auth == 'pat' }}
        run: ./script.sh ${{ matrix.org }} ${{ github.workspace }}/reports/repos.json
        shell: bash
        working-directory: ${{ matrix.composite-action.action }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Extract action name
        id: extract_action_name
        run: |
          action_name=$(basename ${{ matrix.composite-action.action }})
          echo "action_name=$action_name" >> $GITHUB_ENV
          echo "Action name: $action_name"
          echo "formatted_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "Formatted date: $(date +'%Y-%m-%d')"

      - name: Upload ${{ matrix.composite-action.action }} results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.org }}-${{ env.action_name }}-reports-${{ env.formatted_date}}
          path: reports/
          retention-days: 1
