name: GHEC EMU Migration Audit by File

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Please provide an organization name"
        required: true
      repo_file_path:
        description: "Please provide path to the file with repository names relative to repository root path"
        required: true

jobs:
  audit:
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        composite-action:
          - action: repository/actions
            auth: githubapp
          - action: repository/actions-history
            auth: githubapp
          - action: repository/branch-protection-rules
            auth: githubapp
          - action: repository/discussions
            auth: githubapp
          - action: repository/environments
            auth: githubapp
          - action: repository/permissions
            auth: githubapp
          - action: repository/projects
            auth: githubapp
          - action: repository/teams
            auth: githubapp
          - action: repository/users
            auth: githubapp
          - action: repository/webhooks
            auth: githubapp
          #- organization/actions
          - action: organization/apps
            auth: githubapp
          - action: organization/packages
            auth: pat
          # - organization/projects
          - action: organization/secrets
            auth: githubapp
          - action: organization/webhooks
            auth: githubapp

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.ref_name }}

      - name: Copy ${{ github.event.inputs.org_name }} repository file to report folder
        run: |
          mkdir -p "${{ github.workspace }}/reports"
          cp "${{ github.workspace }}/${{ github.event.inputs.repo_file_path }}" "${{ github.workspace }}/reports/repos.json"
        shell: bash

      - name: Get Token
        id: get_workflow_token
        if: ${{ matrix.composite-action.auth == 'githubapp' }}
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.event.inputs.org_name }}

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 18
        if: ${{ matrix.composite-action.action == 'organization/actions' }}

      - name: Run ${{ matrix.composite-action.action }} on ${{ github.event.inputs.org_name }}
        if: ${{ matrix.composite-action.auth == 'githubapp' }}
        run: ./script.sh ${{ github.event.inputs.org_name }} "${{ github.workspace }}/${{ github.event.inputs.repo_file_path }}"
        shell: bash
        working-directory: ${{ matrix.composite-action.action }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Run ${{ matrix.composite-action.action }} on ${{ matrix.org }}
        if: ${{ matrix.composite-action.auth == 'pat' }}
        run: ./script.sh ${{ matrix.org }} ${{ github.workspace }}/reports/repos.json
        shell: bash
        working-directory: ${{ matrix.composite-action.action }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload ${{ matrix.composite-action.action }} results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: ${{ github.event.inputs.org_name }}-reports
          path: reports/
          retention-days: 1
