name: GHEC EMU Migration Audit by File

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Please provide an organization name"
        required: true
      repo_file_path:
        description: "Please provide path to the file with repository names relative to repository root path"
        required: true

jobs:
  audit:
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        composite-action:
          - repository/actions
          - repository/actions-history
          - repository/branch-protection-rules
          - repository/discussions
          - repository/environments
          - repository/permissions
          - repository/projects
          - repository/teams
          - repository/users
          - repository/webhooks
          #- organization/actions
          - organization/apps
          - organization/packages
          # - organization/projects
          - organization/secrets
          - organization/webhooks

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.ref_name }}

      - name: Copy ${{ github.event.inputs.org_name }} repository file to report folder
        run: |
          mkdir -p "${{ github.workspace }}/reports"
          cp "${{ github.workspace }}/${{ github.event.inputs.repo_file_path }}" "${{ github.workspace }}/reports/repos.json"
        shell: bash

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.event.inputs.org_name }}

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 18
        if: ${{ matrix.composite-action == 'organization/actions' }}

      - name: Run ${{ matrix.composite-action }} on ${{ github.event.inputs.org_name }}
        run: ./script.sh ${{ github.event.inputs.org_name }} "${{ github.workspace }}/${{ github.event.inputs.repo_file_path }}"
        shell: bash
        working-directory: ${{ matrix.composite-action }}
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Upload ${{ matrix.composite-action }} results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: ${{ github.event.inputs.org_name }}-reports
          path: reports/
          retention-days: 1
